/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "MyBackend": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "MyDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "MyEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "MySite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "MyVPC": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}